"""Evidence-first Agent understanding and customer simulation testing."""

from .aawo_compat import (
    TesterBlueprint,
    build_aawo_department_dict,
    build_aawo_department_dicts,
    default_test_blueprints,
    register_departments_with_aawo,
    register_with_aawo,
)
from .aawo_runtime import (
    AAWORuntimeUnavailable,
    AAWOTestTeamResult,
    AAWOTestTeamRunner,
    aawo_test_team_spec_data,
    journey_to_aawo_workflow_data,
    require_aawo_runtime,
)
from .adapters import (
    AdapterDescription,
    AsyncJobAdapter,
    CallableAdapter,
    CliAdapter,
    HttpAdapter,
    SessionContext,
    UnderTestAdapter,
)
from .environment import FixtureEnvironment
from .evolution import (
    AAWOEvolutionResult,
    EvolutionApproval,
    EvolutionCanaryMetrics,
    EvolutionGovernor,
    evaluate_evolution_canary,
)
from .ledger import EvidenceLedger
from .models import (
    AgentContractProfile,
    ContractHypothesis,
    Correction,
    CustomerJourney,
    EvidenceLevel,
    EvidenceRef,
    EvolutionProposal,
    FactStatus,
    Finding,
    FindingKind,
    JourneyStep,
    RawObservation,
    RegressionPlan,
    RunStatus,
    Severity,
    StepResult,
    StepStatus,
    TestRun,
)
from .reasoning import (
    PROPOSAL_RESPONSE_SCHEMA,
    OpenAICompatibleReasoner,
    ReasoningProvider,
    ReasoningProviderError,
    ReasoningResponse,
    build_proposal_messages,
    load_managed_env,
    proposal_from_response,
)
from .regression import CorrectionImpactAnalyzer
from .runner import CustomerSimulationRunner
from .understanding import UnderstandingEngine

__all__ = [
    "PROPOSAL_RESPONSE_SCHEMA",
    "AAWOEvolutionResult",
    "AAWORuntimeUnavailable",
    "AAWOTestTeamResult",
    "AAWOTestTeamRunner",
    "AdapterDescription",
    "AgentContractProfile",
    "AsyncJobAdapter",
    "CallableAdapter",
    "CliAdapter",
    "ContractHypothesis",
    "Correction",
    "CorrectionImpactAnalyzer",
    "CustomerJourney",
    "CustomerSimulationRunner",
    "EvidenceLedger",
    "EvidenceLevel",
    "EvidenceRef",
    "EvolutionApproval",
    "EvolutionCanaryMetrics",
    "EvolutionGovernor",
    "EvolutionProposal",
    "FactStatus",
    "Finding",
    "FindingKind",
    "FixtureEnvironment",
    "HttpAdapter",
    "JourneyStep",
    "OpenAICompatibleReasoner",
    "RawObservation",
    "ReasoningProvider",
    "ReasoningProviderError",
    "ReasoningResponse",
    "RegressionPlan",
    "RunStatus",
    "SessionContext",
    "Severity",
    "StepResult",
    "StepStatus",
    "TestRun",
    "TesterBlueprint",
    "UnderTestAdapter",
    "UnderstandingEngine",
    "aawo_test_team_spec_data",
    "build_aawo_department_dict",
    "build_aawo_department_dicts",
    "build_proposal_messages",
    "default_test_blueprints",
    "evaluate_evolution_canary",
    "journey_to_aawo_workflow_data",
    "load_managed_env",
    "proposal_from_response",
    "register_departments_with_aawo",
    "register_with_aawo",
    "require_aawo_runtime",
]
